name: Static Analysis

on:
  push:
    branches:
      - main

  pull_request:

jobs:

  cppcheck:
    name: Check source code

    runs-on: ubuntu-latest
    steps:
    
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: install package dependencies
      run: sudo apt-get install -y cppcheck
    
    - name: Run cppcheck
      run: make check
