name: Static Analysis

on:
  push:
    branches:
      - main
    paths:
      - 'xchange/**'
      - 'redisx/**'
      - 'smax-clib/**'
      - 'smax-postgres/**'
      - 'Makefile'
      - '.github/workflows/check.yml'

  pull_request:
    paths:
      - 'xchange/**'
      - 'redisx/**'
      - 'smax-clib/**'
      - 'smax-postgres/**'
      - 'Makefile'
      - '.github/workflows/check.yml'

jobs:

  cppcheck:
    name: Check source code

    runs-on: ubuntu-latest
    steps:
    
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: install package dependencies
      run: sudo apt-get install -y cppcheck
    
    - name: Run cppcheck
      run: make check
