name: API documentation
permissions:
  contents: read

on:
  release:
    types: [published]

  push:
    branches:
      - main

  pull_request:

jobs:

  apidocs:
    name: Generate API documentation

    runs-on: ubuntu-latest
    steps:

    - name: install doxygen
      run: sudo apt-get install doxygen

    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Generate docs
      run: make dox
